export const inventoryA1 = [
    { codigo: "A1-001", sicafi: "", pf: "", descripcion: "Carrocería: pintura / latas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-002", sicafi: "", pf: "", descripcion: "Presión de las 7 llantas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-003", sicafi: "", pf: "", descripcion: "Derrame de fluidos: /inspeccion general", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-004", sicafi: "", pf: "", descripcion: "Motor: nivel de aciete / nivel liquido frenos / hidraulico / refrigerante radiador / bandas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-005", sicafi: "", pf: "", descripcion: "Encendido del motor: Tablero /plumas delantera y posterior/pito/ pito de retro", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-006", sicafi: "", pf: "", descripcion: "Luces: faros intensos, medias / neblineros/ direccionales /retro / Stop", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-007", sicafi: "", pf: "", descripcion: "Balizas: Lluces de balizas principales /balizas laterales, Flashes delantero y posterior", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-008", sicafi: "", pf: "", descripcion: "Sirena", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-009", sicafi: "", pf: "", descripcion: "Nivel de combustible", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-010", sicafi: "", pf: "", descripcion: "Pantalla de controles", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-011", sicafi: "", pf: "", descripcion: "Encendedor de cigarrillos", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-012", sicafi: "", pf: "", descripcion: "Radio de comunicaciones", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-013", sicafi: "", pf: "", descripcion: "Manual del vehiculo", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-014", sicafi: "", pf: "", descripcion: "Matricula y revision", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-015", sicafi: "", pf: "", descripcion: "Mascarillas quirurgicas (10)", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-016", sicafi: "", pf: "", descripcion: "Caja de guantes de nitrilo", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-017", sicafi: "", pf: "", descripcion: "Tarjetas de triage (10)", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-018", sicafi: "", pf: "", descripcion: "Cintas Scoch para triage (3)", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-019", sicafi: "", pf: "", descripcion: "Cargador adaptador de 12 voltios", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-020", sicafi: "", pf: "", descripcion: "Paño limpiador color rojo", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-021", sicafi: "", pf: "", descripcion: "Guia de respuesta en caso de mergencia", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-022", sicafi: "", pf: "", descripcion: "Gata y llave de ruedas (bolso y accesorios)", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-023", sicafi: "", pf: "", descripcion: "Cinta de peligro", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-024", sicafi: "", pf: "", descripcion: "Caja de herramientas", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-025", sicafi: "", pf: "", descripcion: "Alicate (playo)", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-026", sicafi: "", pf: "", descripcion: "Bolso con protectores para Airbag", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-027", sicafi: "", pf: "", descripcion: "Mandarria pequeña", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-028", sicafi: "", pf: "", descripcion: "Cinta de izado", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-029", sicafi: "", pf: "", descripcion: "Fijador de cabeza pediatrico", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-030", sicafi: "", pf: "", descripcion: "Fel Pediatrica", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-031", sicafi: "", pf: "", descripcion: "Tensiometro recien nacido, neonato y niño", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-032", sicafi: "", pf: "", descripcion: "Llave de pico de loro", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-033", sicafi: "", pf: "", descripcion: "Tabla de hoja de atención con carpeta", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-034", sicafi: "", pf: "", descripcion: "Collarin de adulto", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-035", sicafi: "", pf: "", descripcion: "Collarin pediatrico", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-036", sicafi: "", pf: "", descripcion: "Dispensador de gel antibacterial", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-037", sicafi: "", pf: "", descripcion: "Calentador de fluidos Spencer", ubicacion: "HABITACULO GENERAL", marca: "SPENCER", modelo: "", serie: "" },
    { codigo: "A1-038", sicafi: "", pf: "", descripcion: "Camilla de ruedas SPENCER", ubicacion: "HABITACULO GENERAL", marca: "SPENCER", modelo: "", serie: "" },
    { codigo: "A1-039", sicafi: "", pf: "", descripcion: "Tanque de oxigeno pequeño con flujometro", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-040", sicafi: "", pf: "", descripcion: "Tanque de oxigeno mediano con flujometro", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-041", sicafi: "", pf: "", descripcion: "Basureros (comunes, infecciosos, cortopuzante)", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-042", sicafi: "", pf: "", descripcion: "Extintor de PQS 5lbrs", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-043", sicafi: "", pf: "", descripcion: "Extintor de CO2 5lbrs", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-044", sicafi: "", pf: "", descripcion: "Dispensador de toallas de papel", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-045", sicafi: "", pf: "", descripcion: "Monitor desfribilador con palas", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-046", sicafi: "", pf: "", descripcion: "Succionador fijo", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-047", sicafi: "", pf: "", descripcion: "FEL", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-048", sicafi: "", pf: "", descripcion: "Nebulizador Blanco", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-049", sicafi: "", pf: "", descripcion: "Ferula de traccion", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-050", sicafi: "", pf: "", descripcion: "Letrero de PC / ACV", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-051", sicafi: "", pf: "", descripcion: "Chaleco de extricacion", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-052", sicafi: "", pf: "", descripcion: "BOA", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-053", sicafi: "", pf: "", descripcion: "Collarines (4 adulto, 1 pediatrico)", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-054", sicafi: "", pf: "", descripcion: "Fundas negras / siploc", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-055", sicafi: "", pf: "", descripcion: "Másacaras SCOTT / Full facepiece (4)", ubicacion: "DEBAJO ASIENTO", marca: "SCOTT", modelo: "", serie: "" },
    { codigo: "A1-056", sicafi: "", pf: "", descripcion: "Camilla pala scoop", ubicacion: "ARMARIO OXIGENO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-057", sicafi: "", pf: "", descripcion: "Tanque de oxigeno grande con flujometro", ubicacion: "ARMARIO OXIGENO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-058", sicafi: "", pf: "", descripcion: "Fijador de cabeza con tiras y arañas", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-059", sicafi: "", pf: "", descripcion: "Succionador portatil con estuche", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-060", sicafi: "", pf: "", descripcion: "Kit de ferulas / Cobija", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-061", sicafi: "", pf: "", descripcion: "Colchón de vacio", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-062", sicafi: "", pf: "", descripcion: "Maleta Naranja (Desfibrilador/Monitor)", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-063", sicafi: "", pf: "", descripcion: "Kit de Partos (Pera, recepción, toallas)", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-064", sicafi: "", pf: "", descripcion: "Mascara oxigeno adulto/neonatal", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-065", sicafi: "", pf: "", descripcion: "Campana pinard / Manta termica", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-066", sicafi: "", pf: "", descripcion: "BVM neonato", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-067", sicafi: "", pf: "", descripcion: "BVM pediatrico / adulto (3)", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-068", sicafi: "", pf: "", descripcion: "Glucometro / Tijeras / ARS", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-069", sicafi: "", pf: "", descripcion: "Tensiometro / Fonendo / Oximetros", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-070", sicafi: "", pf: "", descripcion: "Laringoscopio completo", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" }
];

export const inventoryB2 = [
    { codigo: "B2-001", sicafi: "", pf: "", descripcion: "Carrocería: pintura / latas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-002", sicafi: "", pf: "", descripcion: "Presión de las 6 llantas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-003", sicafi: "", pf: "", descripcion: "Derrame de fluidos: /inspeccion general", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-004", sicafi: "", pf: "", descripcion: "Motor: nivel de aciete / nivel liquido frenos / hidraulico / refrigerante radiador / bandas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-005", sicafi: "", pf: "", descripcion: "Encendido del motor: Tablero / nivel de aire / temperatura / plumas / pito", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-006", sicafi: "", pf: "", descripcion: "Acople de la Bomba: 1) motor encendido 2) freno del pie 3) acople", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-007", sicafi: "", pf: "", descripcion: "Luces: faros intensos y medias / direccionales / retro / Stop", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-008", sicafi: "", pf: "", descripcion: "Balizas: Luces de balizas principales / balizas traseras", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-009", sicafi: "", pf: "", descripcion: "Sirena", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-010", sicafi: "", pf: "", descripcion: "Nivel de Combustible", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-011", sicafi: "", pf: "", descripcion: "Nivel de espuma en tanque", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-012", sicafi: "", pf: "", descripcion: "Nivel de agua del tanque", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "B2-013", sicafi: "", pf: "", descripcion: "Mascarillas en funda ziplok (10)", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-014", sicafi: "", pf: "", descripcion: "Caja de guantes de examinación", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-015", sicafi: "", pf: "", descripcion: "Matricula y revision", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-016", sicafi: "", pf: "", descripcion: "Manual de usuario", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-017", sicafi: "", pf: "", descripcion: "Destornilladores (3 estrellas, 3 planos)", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-018", sicafi: "", pf: "", descripcion: "Playo de extención", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-019", sicafi: "", pf: "", descripcion: "Navaja Gerber", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-020", sicafi: "", pf: "", descripcion: "Martillo rompe vidrio (Glass Pum)", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-021", sicafi: "", pf: "", descripcion: "Juego de hexagonales (13 piezas)", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-022", sicafi: "", pf: "", descripcion: "Flexometro", ubicacion: "CABINA-SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-023", sicafi: "", pf: "", descripcion: "SCBA SCOTT (3)", ubicacion: "CABINA", marca: "SCOTT", modelo: "", serie: "" },
    { codigo: "B2-024", sicafi: "", pf: "", descripcion: "Radio Base", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-025", sicafi: "", pf: "", descripcion: "Control para abrir la puerta", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-026", sicafi: "", pf: "", descripcion: "Binoculares", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-027", sicafi: "", pf: "", descripcion: "Pantalla para camaras", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-028", sicafi: "", pf: "", descripcion: "Llaves para gabetas", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-029", sicafi: "", pf: "", descripcion: "Control de wincha", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-030", sicafi: "", pf: "", descripcion: "Linterna Nightstick VIRIBUS naranja", ubicacion: "CABINA", marca: "NIGHTSTICK", modelo: "", serie: "" },
    { codigo: "B2-031", sicafi: "", pf: "", descripcion: "Cargador de Linterna Nightstick", ubicacion: "CABINA", marca: "NIGHTSTICK", modelo: "", serie: "" },
    { codigo: "B2-032", sicafi: "", pf: "", descripcion: "Caja plastica con camara termografica y accesorios", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-033", sicafi: "", pf: "", descripcion: "Flujometro para tanque de oxigeno y pino", ubicacion: "CABINA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-034", sicafi: "", pf: "", descripcion: "Gata y llave de ruedas", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-035", sicafi: "", pf: "", descripcion: "Mandarria de 16lb", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-036", sicafi: "", pf: "", descripcion: "Cizallas amarillas (36\", 30\", 24\")", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-037", sicafi: "", pf: "", descripcion: "Halligan (2)", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-038", sicafi: "", pf: "", descripcion: "Hacha de bombero / Hacha de leñador", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-039", sicafi: "", pf: "", descripcion: "Extintores (10lb CO2, 20lb PQS)", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-040", sicafi: "", pf: "", descripcion: "Bloqueadores de puerta (3)", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-041", sicafi: "", pf: "", descripcion: "Serrucho de jardinero", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-042", sicafi: "", pf: "", descripcion: "Casco de motosierra sthil", ubicacion: "GAVETA 1 DERECHA", marca: "STHIL", modelo: "", serie: "" },
    { codigo: "B2-043", sicafi: "", pf: "", descripcion: "Cinta de peligro", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-044", sicafi: "", pf: "", descripcion: "Motosierra sthil #2", ubicacion: "GAVETA 1 DERECHA", marca: "STHIL", modelo: "", serie: "" },
    { codigo: "B2-045", sicafi: "", pf: "", descripcion: "Juego de 12 Llaves Combinadas", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-046", sicafi: "", pf: "", descripcion: "Playo de extención / Pin remolque", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-047", sicafi: "", pf: "", descripcion: "Martillo bellota / Mandarria de goma", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-048", sicafi: "", pf: "", descripcion: "Linterna Nightstick NSR-1514 (2)", ubicacion: "GAVETA 1 DERECHA", marca: "NIGHTSTICK", modelo: "", serie: "" },
    { codigo: "B2-049", sicafi: "", pf: "", descripcion: "Caja de herramientas / Kit herramientas motosierra", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-050", sicafi: "", pf: "", descripcion: "Par de guantes de cuero", ubicacion: "GAVETA 1 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-051", sicafi: "", pf: "", descripcion: "Equipo Neumatico (Carrito, Cilindros, Mangueras, Regulador, Triplex)", ubicacion: "EQUIPO NEUMATICO", marca: "", modelo: "", serie: "" },
    { codigo: "B2-052", sicafi: "", pf: "", descripcion: "Fijador de cabeza / Maleta cuerda", ubicacion: "GAVETA 2 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-053", sicafi: "", pf: "", descripcion: "Chaleco de extricación / Tanque de oxigeno", ubicacion: "GAVETA 2 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-054", sicafi: "", pf: "", descripcion: "Mangueras para hidraulico (2)", ubicacion: "GAVETA 2 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-055", sicafi: "", pf: "", descripcion: "Maleta Moladora Milwaukee (Moladora, Baterias, Discos, Cargador)", ubicacion: "MALETAS MILWAUKEE", marca: "MILWAUKEE", modelo: "", serie: "" },
    { codigo: "B2-056", sicafi: "", pf: "", descripcion: "Maleta Moto-trosadora Milwaukee (Bateria, Cargador)", ubicacion: "MALETAS MILWAUKEE", marca: "MILWAUKEE", modelo: "", serie: "" },
    { codigo: "B2-057", sicafi: "", pf: "", descripcion: "BVM pediatrico / adulto con mascarilla (2)", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-058", sicafi: "", pf: "", descripcion: "Filtros EPA (2) / Venda hemostatico", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-059", sicafi: "", pf: "", descripcion: "Parche toraxico / DEA / ARS", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-060", sicafi: "", pf: "", descripcion: "Tensiometro / Fonendo / Oximetro / Torniquete", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-061", sicafi: "", pf: "", descripcion: "Termometro / Esparadrapo / Alcohol / Povidin", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-062", sicafi: "", pf: "", descripcion: "Voltaren / Parches oculares / Mantas Termicas", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-063", sicafi: "", pf: "", descripcion: "Caja metalica (Kit 16 piezas e instrumental)", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-064", sicafi: "", pf: "", descripcion: "Glucometro / Kit diagnostico / Guantes quirurgicos", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-065", sicafi: "", pf: "", descripcion: "Kit canulas de guedel / Mascaras reservorio / Laringoscopio", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-066", sicafi: "", pf: "", descripcion: "Vendas varias / Vendas triangulares", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-067", sicafi: "", pf: "", descripcion: "Collarines / Kit ferulas / I-gel", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-068", sicafi: "", pf: "", descripcion: "Tanques reserva SCBA (SCOTT, MSA)", ubicacion: "SOBRE LLANTA DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-069", sicafi: "", pf: "", descripcion: "Protector airbag / Motor hidraulico", ubicacion: "GAVETA 3 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-070", sicafi: "", pf: "", descripcion: "Bolsas neumaticas (grandes, medianas, pequeñas)", ubicacion: "GAVETA 3 DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-071", sicafi: "", pf: "", descripcion: "Maleta Sierra Sable / Rota Martillo Milwaukee", ubicacion: "MALETAS MILWAUKEE", marca: "MILWAUKEE", modelo: "", serie: "" },
    { codigo: "B2-072", sicafi: "", pf: "", descripcion: "Extractor de humo / Trozadora electrica", ubicacion: "GAVETA POSTERIOR", marca: "", modelo: "", serie: "" },
    { codigo: "B2-073", sicafi: "", pf: "", descripcion: "Cintas de izado amarillas (4) / Tecles (4)", ubicacion: "GAVETA POSTERIOR", marca: "", modelo: "", serie: "" },
    { codigo: "B2-074", sicafi: "", pf: "", descripcion: "Equipo Ajax Rescue Tools (Manguera, Pistola, Sinceles)", ubicacion: "EQUIPO AJAX", marca: "", modelo: "", serie: "" },
    { codigo: "B2-075", sicafi: "", pf: "", descripcion: "Cuñas / Manguera 1 3/4 / Reduccion / Piton / Bifurcadoras", ubicacion: "GAVETA 1 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-076", sicafi: "", pf: "", descripcion: "Pata de cabra / Llaves canecas e hidrante", ubicacion: "GAVETA 1 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-077", sicafi: "", pf: "", descripcion: "Conos / Llaves manguera / SCBA SCOTT", ubicacion: "GAVETA 1 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-078", sicafi: "", pf: "", descripcion: "Hilif / Estabilizadores / Tacos y Cuñas madera", ubicacion: "GAVETA 2 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-079", sicafi: "", pf: "", descripcion: "Maleta Rescate Anclaje / Maleta Ferreteria", ubicacion: "MALETAS RESCATE", marca: "", modelo: "", serie: "" },
    { codigo: "B2-080", sicafi: "", pf: "", descripcion: "Kit Rescate Tarabitas y Canopys", ubicacion: "MALETAS RESCATE", marca: "", modelo: "", serie: "" },
    { codigo: "B2-081", sicafi: "", pf: "", descripcion: "Escalerillas madera / Expansor y Cortador hidraulico", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" }
,    { codigo: "B2-082", sicafi: "", pf: "", descripcion: "RAM", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-083", sicafi: "", pf: "", descripcion: "Lona de protección Lukas", ubicacion: "GAVETA 3 IZQUIERDA", marca: "LUKAS", modelo: "", serie: "" },
    { codigo: "B2-084", sicafi: "", pf: "", descripcion: "Cascos agua rapidas (NRS) (2)", ubicacion: "GAVETA 3 IZQUIERDA", marca: "NRS", modelo: "", serie: "" },
    { codigo: "B2-085", sicafi: "", pf: "", descripcion: "Trajes de neopreno (2)", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-086", sicafi: "", pf: "", descripcion: "Cuerdas de rescate aguas rapidas (2)", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-087", sicafi: "", pf: "", descripcion: "Chalecos salva vidas (2)", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-088", sicafi: "", pf: "", descripcion: "Mochila Swtich tank con manguera y bateria", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-089", sicafi: "", pf: "", descripcion: "Barrera absorbente para derrames de hidrocarburos", ubicacion: "GAVETA 3 IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-090", sicafi: "", pf: "", descripcion: "Picos (3)", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-091", sicafi: "", pf: "", descripcion: "Palas (3)", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-092", sicafi: "", pf: "", descripcion: "Azadones (2)", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-093", sicafi: "", pf: "", descripcion: "Canecas de espumogeno (4)", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-094", sicafi: "", pf: "", descripcion: "Manguera para succión de espumogeno", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-095", sicafi: "", pf: "", descripcion: "Escalera plegable", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-096", sicafi: "", pf: "", descripcion: "Lonas de aserrin (2)", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-097", sicafi: "", pf: "", descripcion: "Escobas (2)", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-098", sicafi: "", pf: "", descripcion: "Mcleod", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-099", sicafi: "", pf: "", descripcion: "Escalera de dos cuerpos", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-100", sicafi: "", pf: "", descripcion: "Pescan", ubicacion: "PARTE SUPERIOR GAVETA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-101", sicafi: "", pf: "", descripcion: "Camilla Sket", ubicacion: "PARTE SUPERIOR GAVETA NUEVA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-102", sicafi: "", pf: "", descripcion: "Extenciones color naranja (3)", ubicacion: "PARTE SUPERIOR GAVETA BAJA IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-103", sicafi: "", pf: "", descripcion: "Reflector color amarillo", ubicacion: "PARTE SUPERIOR GAVETA BAJA IZQUIERDA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-104", sicafi: "", pf: "", descripcion: "Tubo de succión de espumogeno", ubicacion: "PARTE SUPERIOR GAVETA BAJA DERECHA", marca: "", modelo: "", serie: "" },
    { codigo: "B2-105", sicafi: "", pf: "", descripcion: "Mangueras 1 1/2 y Piton (7)", ubicacion: "ESTIBADOS", marca: "", modelo: "", serie: "" },
    { codigo: "B2-106", sicafi: "", pf: "", descripcion: "Mangueras 1 1/2 ataque rápido y Piton G-FORCE (4)", ubicacion: "ESTIBADOS", marca: "G-FORCE", modelo: "", serie: "" },
    { codigo: "B2-107", sicafi: "", pf: "", descripcion: "Mangueras 2 1/2 ataque rápido y Piton El Khart Brass (3)", ubicacion: "ESTIBADOS", marca: "El Khart Brass", modelo: "", serie: "" },
    { codigo: "B2-108", sicafi: "", pf: "", descripcion: "Mangueras 2 1/2 25 asas (7)", ubicacion: "ESTIBADOS", marca: "", modelo: "", serie: "" },
    { codigo: "B2-109", sicafi: "", pf: "", descripcion: "Camilla FEEL", ubicacion: "ESTIBADOS", marca: "", modelo: "", serie: "" }
]
