export const fullInventory = [
    { codigo: "A1-001", sicafi: "", pf: "", descripcion: "Carrocería: pintura / latas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-002", sicafi: "", pf: "", descripcion: "Presión de las 7 llantas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-003", sicafi: "", pf: "", descripcion: "Derrame de fluidos: /inspeccion general", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-004", sicafi: "", pf: "", descripcion: "Motor: nivel de aciete / nivel liquido frenos / hidraulico / refrigerante radiador / bandas", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-005", sicafi: "", pf: "", descripcion: "Encendido del motor: Tablero /plumas delantera y posterior/pito/ pito de retro", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-006", sicafi: "", pf: "", descripcion: "Luces: faros intensos, medias / neblineros/ direccionales /retro / Stop", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-007", sicafi: "", pf: "", descripcion: "Balizas: Lluces de balizas principales /balizas laterales, Flashes delantero y posterior", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-008", sicafi: "", pf: "", descripcion: "Sirena", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-009", sicafi: "", pf: "", descripcion: "Nivel de combustible", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-010", sicafi: "", pf: "", descripcion: "Pantalla de controles", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-011", sicafi: "", pf: "", descripcion: "Encendedor de cigarrillos", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-012", sicafi: "", pf: "", descripcion: "Radio de comunicaciones", ubicacion: "DESCRIPCIÓN", marca: "", modelo: "", serie: "" },
    { codigo: "A1-013", sicafi: "", pf: "", descripcion: "Manual del vehiculo", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-014", sicafi: "", pf: "", descripcion: "Matricula y revision", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-015", sicafi: "", pf: "", descripcion: "Mascarillas quirurgicas (10)", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-016", sicafi: "", pf: "", descripcion: "Caja de guantes de nitrilo", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-017", sicafi: "", pf: "", descripcion: "Tarjetas de triage (10)", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-018", sicafi: "", pf: "", descripcion: "Cintas Scoch para triage (3)", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-019", sicafi: "", pf: "", descripcion: "Cargador adaptador de 12 voltios", ubicacion: "SECRETA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-020", sicafi: "", pf: "", descripcion: "Paño limpiador color rojo", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-021", sicafi: "", pf: "", descripcion: "Guia de respuesta en caso de mergencia", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-022", sicafi: "", pf: "", descripcion: "Gata y llave de ruedas (bolso y accesorios)", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-023", sicafi: "", pf: "", descripcion: "Cinta de peligro", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-024", sicafi: "", pf: "", descripcion: "Caja de herramientas", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-025", sicafi: "", pf: "", descripcion: "Alicate (playo)", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-026", sicafi: "", pf: "", descripcion: "Bolso con protectores para Airbag", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-027", sicafi: "", pf: "", descripcion: "Mandarria pequeña", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-028", sicafi: "", pf: "", descripcion: "Cinta de izado", ubicacion: "CABINA CONDUCTOR", marca: "", modelo: "", serie: "" },
    { codigo: "A1-029", sicafi: "", pf: "", descripcion: "Fijador de cabeza pediatrico", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-030", sicafi: "", pf: "", descripcion: "Fel Pediatrica", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-031", sicafi: "", pf: "", descripcion: "Tensiometro recien nacido, neonato y niño", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-032", sicafi: "", pf: "", descripcion: "Llave de pico de loro", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-033", sicafi: "", pf: "", descripcion: "Tabla de hoja de atención con carpeta", ubicacion: "VITRINA 1", marca: "", modelo: "", serie: "" },
    { codigo: "A1-034", sicafi: "", pf: "", descripcion: "Collarin de adulto", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-035", sicafi: "", pf: "", descripcion: "Collarin pediatrico", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-036", sicafi: "", pf: "", descripcion: "Dispensador de gel antibacterial", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-037", sicafi: "", pf: "", descripcion: "Calentador de fluidos Spencer", ubicacion: "HABITACULO GENERAL", marca: "SPENCER", modelo: "", serie: "" },
    { codigo: "A1-038", sicafi: "", pf: "", descripcion: "Camilla de ruedas SPENCER", ubicacion: "HABITACULO GENERAL", marca: "SPENCER", modelo: "", serie: "" },
    { codigo: "A1-039", sicafi: "", pf: "", descripcion: "Tanque de oxigeno pequeño con flujometro", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-040", sicafi: "", pf: "", descripcion: "Tanque de oxigeno mediano con flujometro", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-041", sicafi: "", pf: "", descripcion: "Basureros (comunes, infecciosos, cortopuzante)", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-042", sicafi: "", pf: "", descripcion: "Extintor de PQS 5lbrs", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-043", sicafi: "", pf: "", descripcion: "Extintor de CO2 5lbrs", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-044", sicafi: "", pf: "", descripcion: "Dispensador de toallas de papel", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-045", sicafi: "", pf: "", descripcion: "Monitor desfribilador con palas", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-046", sicafi: "", pf: "", descripcion: "Succionador fijo", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-047", sicafi: "", pf: "", descripcion: "FEL", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-048", sicafi: "", pf: "", descripcion: "Nebulizador Blanco", ubicacion: "HABITACULO GENERAL", marca: "", modelo: "", serie: "" },
    { codigo: "A1-049", sicafi: "", pf: "", descripcion: "Ferula de traccion", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-050", sicafi: "", pf: "", descripcion: "Letrero de PC / ACV", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-051", sicafi: "", pf: "", descripcion: "Chaleco de extricacion", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-052", sicafi: "", pf: "", descripcion: "BOA", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-053", sicafi: "", pf: "", descripcion: "Collarines (4 adulto, 1 pediatrico)", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-054", sicafi: "", pf: "", descripcion: "Fundas negras / siploc", ubicacion: "DEBAJO ASIENTO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-055", sicafi: "", pf: "", descripcion: "Másacaras SCOTT / Full facepiece (4)", ubicacion: "DEBAJO ASIENTO", marca: "SCOTT", modelo: "", serie: "" },
    { codigo: "A1-056", sicafi: "", pf: "", descripcion: "Camilla pala scoop", ubicacion: "ARMARIO OXIGENO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-057", sicafi: "", pf: "", descripcion: "Tanque de oxigeno grande con flujometro", ubicacion: "ARMARIO OXIGENO", marca: "", modelo: "", serie: "" },
    { codigo: "A1-058", sicafi: "", pf: "", descripcion: "Fijador de cabeza con tiras y arañas", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-059", sicafi: "", pf: "", descripcion: "Succionador portatil con estuche", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-060", sicafi: "", pf: "", descripcion: "Kit de ferulas / Cobija", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-061", sicafi: "", pf: "", descripcion: "Colchón de vacio", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-062", sicafi: "", pf: "", descripcion: "Maleta Naranja (Desfibrilador/Monitor)", ubicacion: "ARMARIO MALETAS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-063", sicafi: "", pf: "", descripcion: "Kit de Partos (Pera, recepción, toallas)", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-064", sicafi: "", pf: "", descripcion: "Mascara oxigeno adulto/neonatal", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-065", sicafi: "", pf: "", descripcion: "Campana pinard / Manta termica", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-066", sicafi: "", pf: "", descripcion: "BVM neonato", ubicacion: "MALETA PARTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-067", sicafi: "", pf: "", descripcion: "BVM pediatrico / adulto (3)", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-068", sicafi: "", pf: "", descripcion: "Glucometro / Tijeras / ARS", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-069", sicafi: "", pf: "", descripcion: "Tensiometro / Fonendo / Oximetros", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-070", sicafi: "", pf: "", descripcion: "Laringoscopio completo", ubicacion: "MALETA ROJA", marca: "", modelo: "", serie: "" },
    { codigo: "A1-100", sicafi: "", pf: "", descripcion: "Kit intoxicaciones", ubicacion: "VITRINA 2", marca: "", modelo: "", serie: "" },
    { codigo: "A1-101", sicafi: "", pf: "", descripcion: "Dopler fetal", ubicacion: "VITRINA 2", marca: "", modelo: "", serie: "" },
    { codigo: "A1-102", sicafi: "", pf: "", descripcion: "Sueros y Equipos Venoclisis", ubicacion: "VITRINA 2", marca: "", modelo: "", serie: "" },
    { codigo: "A1-103", sicafi: "", pf: "", descripcion: "Ampollas Medicamentos Varias", ubicacion: "MEDICAMENTOS", marca: "", modelo: "", serie: "" },
    { codigo: "A1-104", sicafi: "", pf: "", descripcion: "Pastillas Medicamentos Varias", ubicacion: "MEDICAMENTOS", marca: "", modelo: "", serie: "" }
];
